apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  storageClassName: nvcf-function-storage-sc
  volumeMode: Filesystem
