apiVersion: v1
kind: Service
metadata:
  name: entrypoint
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 8000
      targetPort: {{ .Values.inferencePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}