apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "multi-node-task-test.name" . }}
  labels:
    {{- include "multi-node-task-test.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "multi-node-task-test.name" . }}-headless
  podManagementPolicy: Parallel
  replicas: {{ .Values.nodesPerInstance }}
  selector:
    matchLabels:
      {{- include "multi-node-task-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multi-node-task-test.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: temp
          emptyDir: {}
      {{- if .Values.ngcImagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.ngcImagePullSecretName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /tmp
              name: temp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODES_PER_INSTANCE
              value: {{ .Values.nodesPerInstance | quote }}
            - name: NVCT_NCA_ID
              value: {{ .Values.nvctNcaId }}
            - name: NVCT_TASK_ID
              value: {{ .Values.nvctTaskId }}
            - name: NVCT_TASK_NAME
              value: {{ .Values.nvctTaskName }}
            - name: NVCT_RESULTS_DIR
              value: {{ .Values.nvctResultsDir }}
            - name: NVCT_PROGRESS_FILE_PATH
              value: {{ .Values.nvctProgressFilePath }}
            - name: NUM_GPUS
              value: {{ .Values.gpusPerNode | quote }}
            - name: NUM_NODES
              value: {{ .Values.nodesPerInstance | quote }}
            - name: HEADLESS_SERVICE_NAME
              value: {{ include "multi-node-task-test.name" . }}-headless
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
