apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    dra.nvcf.nvidia.io/required-nvlink-domain-index: "0" # force all nodes to use the same NVLink domain
  name: {{ include "multi-node-test.name" . }}
  labels:
    {{- include "multi-node-test.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "multi-node-test.name" . }}-headless
  podManagementPolicy: Parallel
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.nodesPerInstance }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "multi-node-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multi-node-test.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: temp
          emptyDir: {}
      {{- if .Values.ngcImagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.ngcImagePullSecretName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /tmp
              name: temp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODES_PER_INSTANCE
              value: {{ .Values.nodesPerInstance | quote }}
            - name: HEADLESS_SERVICE_NAME
              value: {{ include "multi-node-test.name" . }}-headless
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
